package com.juanalejop.backend.domain;

import static com.juanalejop.backend.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class EventoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAllPropertiesEquals(Evento expected, Evento actual) {
        assertEventoAutoGeneratedPropertiesEquals(expected, actual);
        assertEventoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAllUpdatablePropertiesEquals(Evento expected, Evento actual) {
        assertEventoUpdatableFieldsEquals(expected, actual);
        assertEventoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAutoGeneratedPropertiesEquals(Evento expected, Evento actual) {
        assertThat(actual)
            .as("Verify Evento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoUpdatableFieldsEquals(Evento expected, Evento actual) {
        assertThat(actual)
            .as("Verify Evento relevant properties")
            .satisfies(a -> assertThat(a.getIdCatedra()).as("check idCatedra").isEqualTo(expected.getIdCatedra()))
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getResumen()).as("check resumen").isEqualTo(expected.getResumen()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a ->
                assertThat(a.getFechaHora())
                    .as("check fechaHora")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaHora())
            )
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getImagenUrl()).as("check imagenUrl").isEqualTo(expected.getImagenUrl()))
            .satisfies(a -> assertThat(a.getPrecio()).as("check precio").isEqualTo(expected.getPrecio()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoUpdatableRelationshipsEquals(Evento expected, Evento actual) {
        // empty method
    }
}
